List universityDepartment = [
    "Lütfen bir bölüm seçin",
    "Eğitim Fakültesi",
    "Fen-Edebiyat Fakültesi",
    "Mühendislik Mimarlık Fakültesi",
    "Ziraat Fakültesi",
    "İktisadi ve İdari Bilimler Fakültesi",
    "İletişim Fakültesi",
    "Hukuk Fakültesi",
    "İlahiyat Fakültesi",
    "Tıp Fakültesi",
    "Bilgisayar Mühendisliği",
    "Elektrik Elektronik Mühendisliği",
    "Gıda Mühendisliği",
    "Çevre  Mühendisliği",
    "Biyomedikal Mühendisliği",
    "Endüstri Mühendisliği",
    "İnşaat  Mühendisliği",
    "Jeoloji  Mühendisliği",
    "Maden Mühendisliği",
    "Makine Mühendisliği",
];